config/routes.rb
Rails.application.routes.draw do

  root :to => 'projects#index'

  resources :user_sessions
  resources :users

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :pledges
  resources :rewards
  resources :projects do
    resources :reviews, only: [:show, :create, :destroy]
  end

end

app/models/reward.rb
class Reward < ActiveRecord::Base
  has_many :pledges
  belongs_to :user
  belongs_to :project

  def remaining
    pledge_limit - pledges.count
  end

end

app/controllers/rewards_controller.rb
# class RewardsController < ApplicationController
  
  # def index
  #   @rewards = Reward.all
  # end

  # def show
  #   @reward = Reward.find(params[:id])
  # end

  # def new
  #   @reward = Reward.new
  # end

  # def create
  #   @reward = Reward.new(reward_params)

  #   if @reward.save
  #     redirect_to rewards_url
  #   else
  #     render 'new'
  #   end
  # end

  # def edit
  #   @reward = Reward.find(params[:id])
  # end

  # def update
  #   @reward = Reward.find(params[:id])
  #   if @reward.update_attributes(reward_params)
  #     redirect_to reward_path(@reward)
  #   else
  #     # render :edit
  #     redirect_to edit_project_reward_path(@project, @reward)
  #   end
  # end

  # def destroy
  #   @reward = Reward.find(params[:id])
  #   @reward.destroy
  #   redirect_to rewards_path
  # end

  # private
  # def reward_params
  #   params.require(:reward).permit(:description, :pledge_limit)
#   end

# end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/rewards/_reward.html.erb
<p>
  For <%= number_to_currency reward.amount %>, 
  you get: <%= reward.description %>! 
  (<%= reward.remaining %> remaining)
  
  <%= form_tag pledges_path do %>
    <%= hidden_field_tag "reward_id", reward.id %> 
    <%= submit_tag "Pledge" %>
  <% end %>
</p>

app/views/rewards/edit.html.erb
<h1>Edit <%= @reward.amount %></h1>

<%= form_for @reward do |l| %> 
  <div class="field">
    <div><%= l.label :pledge_limit %></div>
    <%= l.text_field :pledge_limit %> <br>
  </div>
  <div class="field">
    <div><%= l.label :description %></div>
    <%= l.text_area :description %> <br>
  </div>

  <div class="action">
    <%= l.submit %>
  </div>
  <% end %>

  <%= link_to "Back", reward_path(@reward) %>

app/views/rewards/index.html.erb
<h1>This is where you can see all index of rewards!</h1>

<ul>
<% @rewards.each do |reward| %>
  <li><%= reward.pledge_limit %></li>
  <li><%= reward.description %></li>
  <%= link_to "See Reward", reward_path(reward) %>
  <%end%>
</ul>

app/views/rewards/new.html.erb
<h1>Rewards Form</h1>

<%= form_for @reward do |l| %> 

  <div class="field">
    <div><%= l.label :pledge_limit %></div>
    <%= l.text_field :pledge_limit %> <br>
  </div>
  <div class="field">
    <div><%= l.label :description %></div>
    <%= l.text_area :description %> <br>
  </div>
  <div class="action">
    <%= l.submit %>
  </div>

  <% end %>
3

app/views/rewards/show.html.erb
<h1>Reward</h1>

<div class = "reward_description">
  <div>
    <%= @reward.pledge_limit %>
  </div> 
  <div>
  <%= @reward.description %>
  </div>
</div>

<div>
  <%= link_to "Edit", edit_reward_path %> 
</div>