config/routes.rb
Rails.application.routes.draw do

  root :to => 'projects#index'

  resources :user_sessions
  resources :users

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :pledges
  resources :rewards
  resources :projects do
    resources :reviews, only: [:show, :create, :destroy]
  end

end

app/models/project.rb
class Project < ActiveRecord::Base

  has_many :reviews
  has_many :pledges
  has_many :rewards
  accepts_nested_attributes_for :rewards, reject_if: :all_blank, allow_destroy: true
  # accepts_nested_attributes_for :pledges
  belongs_to :user


  def total_pledged
    pledges.sum(:amount)    
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource

  def index
    # Storing arrays into @projects
    @projects = if params[:search]
      # The code below will produce the same results
      # Project.where("name ILIKE?", "%#{params[:search]}%")
      Project.where("LOWER(name) LIKE LOWER(?)", "%#{params[:search]}%")
      # Project.where("LOWER(name) LIKE LOWER(?)", "%#{params[:search]}%")
    else
      Project.all
    end

    respond_to do |format|
      #renders index.html.erb
      format.html 
      #render index.js.erb
      format.js
    end
  end

  def show
	  @project = Project.find(params[:id])
    if current_user
      @review = @project.reviews.build
    end
  end


  def new
    @project = Project.new
    # Don't need the code below anymore due to cocoon gem!
    # 3.times { @project.rewards.build } 
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to projects_url
    else
      render 'new'
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
  	@project = Project.find(params[:id])
    if @project.update_attributes(project_params)
    redirect_to project_path(@project)
      else
      render :edit
    end 
  end

  def destroy
  	@project =Project.find(params[:id])
  	@project.destroy
  	redirect_to projects_path
  end


  private
  def project_params
    params.require(:project).permit(:name, :description, :funding_goal, :start_date, :end_date, rewards_attributes: [:id, :pledge_limit, :amount, :description, :_destroy])
    end
  end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project do |l| %> 
  <div class="field">
    <div><%= l.label :name %></div>
    <%= l.text_field :name %> <br>
  </div>
  <div class="field">
    <div><%= l.label :description %></div>
    <%= l.text_area :description %> <br>
  </div>
  <div class="field">
    <div><%= l.label :funding_goal %></div>
    <%= l.text_field :funding_goal, :placeholder => "eg. 1000" %> <br>
    <!--:input_html => { :value => 'eg. 1000' } -->
  </div>
  <div class="field">
    <div><%= l.label :start_date %></div>
    <%= l.date_select :start_date %><br>
  </div>
    <div class="field">
    <div><%= l.label :end_date %></div>
    <%= l.date_select :end_date %><br>
  </div>

<!-- Adding a nested Rewards form. It's possible through the associations made between projects and rewards -->

  <h1>Add Rewards</h1>
  <div id= "rewards">
    <%= l.fields_for :rewards do |reward_fields| %>
      <%= render 'reward_fields', f: reward_fields %>
    <% end %>
  
    <div class = "links">
      <%= link_to_add_association 'add reward', l, :rewards %>
    </div>

  </div>
    <!-- when time add a picture -->

    
  <%= l.submit %>
    
  <% end %>
 

app/views/projects/_project.html.erb
  <div>
    <p>Project Name: <%= project.name %></p>
    <p>Project Description: <%= project.description %></p>
    <p>Funding Goal: <%= project.funding_goal %></p>
    <p>Project Start Date: <%= project.start_date %></p>
    <p>Project Finish Date: <%= project.end_date %></p>
     <%= link_to "See project", project_path(project) %>
  </div>

app/views/projects/_reward_fields.html.erb
<div class = "nested-fields">
  <div class = "field">
    <%= f.label :amount %>
    <%= f.text_field :amount, :placeholder => "amount they give"  %>
  </div>
  
  <div class = "field">
    <%= f.label :description %>
    <%= f.text_field :description, :placeholder => "what they get" %>
  </div>
  <p></p>
    <div class = "field">
    <%= f.label :pledge_limit %>
    <%= f.text_field :pledge_limit, :placeholder => "number of pledgers" %>
  </div>
  

  <%= link_to_remove_association "remove task", f %>

</div>  

app/views/projects/edit.html.erb
<h1>Edit <% @project.name %></h1>
<%= render 'form' %> 

app/views/projects/index.html.erb
<h1>Punchface</h1>

<% if can? :create, Project %>
  <%= link_to "New Project", new_project_path %>
<% end %>

<div class = "search">
  <%= form_tag projects_path, method: :get, authentication: false, id:'search-form' do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search" %>
  <% end %>  
</div>

<div id="projects">
  <%= render @projects %>
</div>

app/views/projects/index.js.erb
$('#projects').html("<%= j(render @projects) %>");  

app/views/projects/new.html.erb
<h1>Add a Project</h1>
<%= render 'form' %> 

app/views/projects/show.html.erb
<h1>Show Project</h1>
<div class="project_list">
  <div><%= @project.name %></div>
  <div><%= @project.description %></div>
  <div><%= @project.funding_goal %></div>
  <div><%= @project.end_date %></div> 
  <div><%= number_to_currency @project.total_pledged %></div>

   <div><%= link_to "Back", projects_path %>
  <div> <%= link_to "Edit" , edit_project_url(@project) %></div>
  <div> <%= link_to "Delete" , @project, method: :delete, data: {confirm:"Are you sure?"}%></div>

  <!--removed alligator example of nested
   link_to "Edit" , edit_restaurant_reservation_url(@restaurant, reservation) 
   < link_to "Delete", @restaurant, :class =>"inner_back_btns", method: :delete, data: {confirm:"Are you sure?"} >-->

</div>  


<!-- =============================================================================== -->

<!-- The code below is equivalent. Need to add alligator tags -->
<%= render @project.rewards %>


<!-- render partial: "rewards/reward", collection: @project.rewards -->


<!--  @project.rewards.each do |reward| 
   render partial: 'rewards/reward', locals: {reward: reward} 
 end 
 -->

 <!-- =============================================================================== -->

<!-- This code below will show the project's reviews and displays the user's email that created this comment -->

<h3>Reviews</h3>

Reviews for <%= @project.name %>

<div class="review-list">
  <%= render :partial => 'reviews/review', :collection => @project.reviews %>
</div>

 <!-- =============================================================================== -->

<!-- Showing forms if current user is logged in, else links to login to add a review"
 -->

<% if current_user %>
  <h4>New Review</h4>

  <%= form_for([@project, @review], :remote => true) do |f| %>
    <% if @review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>
        
        <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :comment %><br/>
      <%= f.text_area :comment %>      
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

<%else%>
  <p>Please <%= link_to "log in", new_session_path %> to add a review.</p>
<% end %>